# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: website-template
          # A file, directory or wildcard pattern that describes what to upload
          path: index.html
          # The desired behavior if no files are found using the provided path.
  cd-dev:
    name: CD - DEV
    environment:
      name: dev
    runs-on: ubuntu-latest
    needs: [build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          # Artifact name
          name: website-template
          path: website-template
      - name: Upload S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          # aws key id
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws bucket name
          aws_bucket: sitedomanu
          # directory to upload
          source_dir: website-template
          # destination directory for upload
          destination_dir: /
